monitor = HDMI-A-2, preferred, auto, 1, transform, 2

input {
    kb_layout = us
}

general {
    gaps_in = 5
    gaps_out = 5

    layout = dwindle
}

decoration {
    # TODO: styling
}

misc {
    disable_hyprland_logo = true
}

exec-once = noctalia

$mod = SUPER

bind = $mod, RETURN, exec, kitty
bind = $mod, SHIFT, T, exec, kitty # Drop eventually. Nice to have in the VM.
bind = $mod, D, exec, fuzzel

bind = $mod, Q, killactive

bind = $mod, LEFT, movefocus, l
bind = $mod, RIGHT, movefocus, r
bind = $mod, UP, movefocus, u
bind = $mod, DOWN, movefocus, d

bind = $mod SHIFT, LEFT, movewindow, l
bind = $mod SHIFT, RIGHT, movewindow, r

bind = $mod, J, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, I, movefocus, u
bind = $mod, K, movefocus, d

bind = $mod SHIFT, Q, exit